global:
  resolve_timeout: 5m

route:
  group_by: ['instance', 'severity']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'webhook-receiver'
  routes:
    - matchers:
        - alertname="High CPU Load"
      receiver: 'webhook-receiver'

receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://172.17.0.1:9999/webhook'
        send_resolved: true